print(pcall(error, "plain"))
print(pcall(error, "msg", 0))
local ok, e = pcall(error, {code = 42})
print(ok, type(e), e.code)
print(pcall(function() local t = nil; return t.x end))
print(pcall(function() return 1 + nil end))
print(pcall(function() return "a" < 1 end))
print(pcall(function() return {} < {} end))
print(pcall(function() return #nil end))
print(pcall(function() return ("x")() end))
print(pcall(function() undefined_fn() end))
print(pcall(function() return 1 // 0 end))
print(pcall(function() return 1 % 0 end))
print(pcall(function() return "abc" + 1 end))
print(pcall(function() return "10" + 1 end), pcall(function() return "0x10" * 2 end))
print(pcall(string.rep))
print(pcall(setmetatable, 1, {}))
print(select("#", pcall(function() return 1, 2, 3 end)))
print(xpcall(function() error("deep") end, function(m) return "handled: " .. m end))
local function thrower(n) if n == 0 then error("bottom") end return thrower(n - 1) end
print(pcall(thrower, 5))
print(pcall(assert, false))
print(pcall(assert, nil, "custom"))
print(pcall(assert, 1, 2))
local ok2, err2 = pcall(function()
  local ok3, err3 = pcall(error, "inner")
  error("outer after " .. tostring(err3), 0)
end)
print(ok2, err2)
print(tostring(nil) .. "|" .. tostring(false))
print(pcall(function() local a = {}; a[nil] = 1 end))
print(pcall(next, {}, "missing"))
print(math.tointeger(3.0), math.tointeger(3.5), math.tointeger("8"))
print(pcall(function() return 1 & 1.5 end))
