print(pcall(function() string.rep() end))
print(pcall(function() local r = string.rep; r() end))
print(pcall(function() ("x"):rep() end))
print(pcall(function() assert(false) end))
print(pcall(function() assert(nil, "m") end))
print(pcall(function() setmetatable(1, {}) end))
print(pcall(function() error("e") end))
print(pcall(function() error("e", 2) end))
print(pcall(function() local t = setmetatable({}, {__index = function(t, k) error("idx " .. k) end}); return t.foo end))
print(pcall(function() table.insert(nil, 1) end))
print(pcall(function() ("x"):bad() end))
print(pcall(function() local s = "a" .. {} end))
print(pcall(function() return -{} end))
print(pcall(function() return 1 < "x" end))
print(pcall(function() for i = 1, "x" do end end))
print(pcall(function() return math.floor("a") end))
print(pcall(string.format, "%d", 1.5))
print(pcall(function() return ("%d"):format(1.5) end))
print(pcall(function() return tostring() end))
print(pcall(ipairs))
print(pcall(function() local a; a.b.c = 1 end))
print(pcall(function() x.y = 1 end))
print(pcall(function() return 2^63 | 0 end))
