print(("Hello"):len(), ("Hello"):sub(2, 3), ("Hello"):sub(-3), ("Hello"):sub(2), ("Hello"):sub(0), ("Hello"):sub(10))
print(string.byte("ABC", 1, 3), string.char(72, 105), ("x"):rep(0), ("ab"):rep(3))
print(string.format("%d %5d %-5d| %05d %+d", 42, 42, 42, 42, 42))
print(string.format("%.3f %e %g %g %g", math.pi, 12345.678, 0.0001, 1e20, 100))
print(string.format("%s %s %s %10s|%-10s|", 1, 1.5, true, "right", "left"))
print(string.format("%x %X %o %c %%", 255, 255, 8, 65))
print(string.format("%q", "line\nbreak \"quoted\" \\ end"))
print(string.find("the quick brown fox", "quick"), string.find("a.b", ".", 1, true), string.find("abc", "x"))
print(string.find("hello", "l", -2), string.find("hello", "", 10), string.find("hello", "", 6))
print(string.match("2024-01-15", "(%d+)-(%d+)-(%d+)"))
print(string.match("  trim me  ", "^%s*(.-)%s*$"))
print(string.match("key = value", "(%w+)%s*=%s*(%w+)"))
print(string.match("hello", "()ll()"))
print(string.match("[[nested]]", "%[(%b[])%]"))
print(string.gsub("hello world", "(%w+)", "<%1>"))
print(string.gsub("hello world", "%w+", function(w) return w:upper() end))
print(string.gsub("$name is $age", "%$(%w+)", {name = "Bob", age = 42}))
print(string.gsub("abc", "", "-"))
print(string.gsub("one two three", "(%w+) (%w+)", "%2 %1", 1))
print(string.gsub("THE (quick) fox", "%f[%a]%a+", "W"))
local words = {}
for k, v in string.gmatch("a=1, b=2, c=3", "(%w+)=(%w+)") do words[#words + 1] = k .. ":" .. v end
print(table.concat(words, " "))
print(("CamelCaseString"):gsub("(%u)", " %1"))
print(("%d items"):format(3), ("x"):upper():lower())
local s = "count: 10"
print(tonumber(s:match("%d+")) + 1)
print(#"\0\1\2", "\65\066\x43", "\u{48}\u{49}", "tab\there", 'single \'q\'')
print([[long
string]], [==[with ]] inside]==])
print(("a,b,,c"):find(",", 1, true), ("a b"):match("^(%S+)"))
print(string.reverse("stressed"), string.lower("MiXeD"), string.upper("MiXeD"))
print(tostring(123), tostring(-0.0), tostring(1e15), tostring(1e16), tostring(2^63), tostring(0.1))
print(10 .. 20, 1.5 .. "", -1 .. "")
